// List of whitelisted URLs
const newsWebsites = [
    "nytimes.com",
    "bbc.com",
    "cnn.com",
    "theguardian.com",
    "washingtonpost.com",
    "reuters.com",
    "bloomberg.com",
    "forbes.com",
    "wsj.com",
    "nbcnews.com",
    "abcnews.go.com",
    "cbsnews.com",
    "usatoday.com",
    "latimes.com",
    "npr.org",
    "news.yahoo.com",
    "huffpost.com",
    "foxnews.com",
    "msnbc.com",
    "aljazeera.com",
    "politico.com",
    "time.com",
    "newsweek.com",
    "economist.com",
    "ft.com",
    "vox.com",
    "buzzfeednews.com",
    "vice.com",
    "theatlantic.com",
    "slate.com",
    "newyorker.com",
    "propublica.org",
    "axios.com",
    "thehill.com",
    "nationalgeographic.com",
    "scientificamerican.com",
    "techcrunch.com",
    "engadget.com",
    "wired.com",
    "cnet.com",
    "mashable.com",
    "gizmodo.com",
    "arstechnica.com",
    "theverge.com",
    "zdnet.com",
    "pcmag.com",
    "tomshardware.com",
    "anandtech.com",
    "techradar.com",
    "digitaltrends.com",
    "bgr.com",
    "slashgear.com",
    "androidauthority.com",
    "iphonehacks.com",
    "macrumors.com",
    "9to5mac.com",
    "appleinsider.com",
    "cultofmac.com",
    "imore.com",
    "androidcentral.com",
    "windowscentral.com",
    "surfaceproartist.com",
    "chromestory.com",
    "liliputing.com",
    "notebookcheck.net",
    "ultrabookreview.com",
    "tabletpcreview.com",
    "pocket-lint.com",
    "stuff.tv",
    "whathifi.com",
    "trustedreviews.com",
    "expertreviews.co.uk",
    "techadvisor.co.uk",
    "computerworld.com",
    "infoworld.com",
    "networkworld.com",
    "cio.com",
    "itworld.com",
    "techworld.com",
    "pcworld.com",
    "macworld.com",
    "linuxworld.com",
    "unixmen.com",
    "fossbytes.com",
    "opensource.com",
    "lwn.net",
    "phoronix.com",
    "kernel.org",
    "debian.org",
    "ubuntu.com",
    "fedora.org",
    "opensuse.org",
    "archlinux.org",
    "gentoo.org",
    "slackware.com",
    "linuxmint.com",
    "elementary.io",
    "zorinos.com",
    "deepin.org",
    "manjaro.org",
    "kubuntu.org",
    "lubuntu.net",
    "xubuntu.org",
    "ubuntustudio.org",
    "ubuntu-mate.org",
    "ubuntu-budgie.org",
    "ubuntu-gnome.org",
    "ubuntu-kylin.org",
    "ubuntu-touch.io",
    "ubports.com",
    "ubuntuone.com",
    "ubuntuforums.org",
    "askubuntu.com",
    "ubuntu.com",
    "canonical.com",
    "launchpad.net",
    "ppa.launchpad.net",
    "apt.ubuntu.com",
    "packages.ubuntu.com",
    "security.ubuntu.com",
    "wiki.ubuntu.com",
    "help.ubuntu.com",
    "community.ubuntu.com",
    "developer.ubuntu.com",
    "design.ubuntu.com",
    "docs.ubuntu.com",
    "downloads.ubuntu.com",
    "releases.ubuntu.com",
    "cdimage.ubuntu.com",
    "images.ubuntu.com",
    "snapcraft.io",
    "flathub.org",
    "appimage.org",
    "portableapps.com",
    "ninite.com",
    "chocolatey.org",
    "scoop.sh",
    "homebrew.sh",
    "macports.org",
    "finkproject.org",
    "pkgsrc.org",
    "portsnap.org",
    "portage.org",
    "apt-get.org",
    "yum.org",
    "dnf.org",
    "pacman.org",
    "zypper.org",
    "emerge.org",
    "install.sh",
    "setup.exe",
    "msi.org",
    "dmg.org",
    "iso.org",
    "img.org",
    "vmdk.org",
    "qcow2.org",
    "raw.org",
    "vdi.org",
    "vhd.org",
    "vhdx.org",
    "ova.org",
    "ovf.org",
    "pvm.org",
    "pvs.org",
    "pvt.org",
    "pwc.org",
    "pwn.org",
    "pwr.org",
    "pxe.org",
    "pxi.org",
    "pxm.org",
    "pxp.org",
    "pxr.org",
    "pxs.org",
    "pxt.org",
    "pxu.org",
    "pxv.org",
    "pxw.org",
    "pxx.org",
    "pxy.org",
    "pxz.org",
    "py.org",
    "pyc.org",
    "pyd.org",
    "pyo.org",
    "pyw.org",
    "pyx.org",
    "pyz.org",
    "pza.org",
    "pzb.org",
    "pzc.org",
    "pzd.org",
    "pze.org",
    "pzf.org",
    "pzg.org",
    "pzh.org",
    "pzi.org",
    "pzj.org",
    "pzk.org",
    "pzl.org",
    "pzm.org",
    "pzn.org",
    "pzo.org",
    "pzp.org",
    "pzq.org",
    "pzr.org",
    "pzs.org",
    "pzt.org",
    "pzu.org",
    "pzv.org",
    "pzw.org",
    "pzx.org",
    "pzy.org",
    "pzz.org"
];

function hasDuplicates(array) {
    const seen = new Set();

    for (const element of array) {
        if (seen.has(element)) {
            return true;
        }
        seen.add(element);
    }

    return false;
}

console.log(hasDuplicates(newsWebsites));

// Function to check if a URL is whitelisted
function isWhitelisted(url) {
    return whitelist.some(domain => url.includes(domain));
}

// Listen for tab updates to check the URL
chrome.tabs.onUpdated.addListener((tabId, changeInfo, tab) => {
    if (changeInfo.status === 'complete' && tab.url) {
        if (!isWhitelisted(tab.url)) {
            // Disable the extension for this tab
            chrome.scripting.executeScript({
                target: { tabId: tabId },
                function: disableExtension
            });
        }
    }
});

// Function to disable the extension
function disableExtension() {
    // Remove the bubble container if it exists
    const bubbleContainer = document.getElementById('bubble-container');
    if (bubbleContainer) {
        bubbleContainer.remove();
    }
}